"use client";

import { motion } from "framer-motion";
import { CheckCircle, Circle, BookOpen, Code, Users, ArrowDown, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

const iconMap = {
  learn: BookOpen,
  code: Code,
  network: Users,
  default: Circle,
};

const colors = [
  "from-blue-500 to-indigo-600",
  "from-emerald-500 to-teal-600",
  "from-purple-500 to-indigo-600",
  "from-orange-500 to-red-600",
  "from-cyan-500 to-blue-600",
  "from-pink-500 to-purple-600",
];

export default function RoadmapDisplay({ roadmap }) {
  const downloadRoadmap = () => {
    // Create a canvas for the roadmap image
    const canvas = document.createElement('canvas');
    canvas.width = 1200;
    canvas.height = 1600;
    const ctx = canvas.getContext('2d');

    // Background
    const gradient = ctx.createLinearGradient(0, 0, 1200, 1600);
    gradient.addColorStop(0, '#0a0a0a');
    gradient.addColorStop(1, '#171717');
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, 1200, 1600);

    // Title
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 48px Arial';
    ctx.textAlign = 'center';
    ctx.fillText(roadmap.title, 600, 80);

    // Subtitle
    ctx.fillStyle = '#94a3b8';
    ctx.font = '24px Arial';
    ctx.fillText('Career Development Roadmap', 600, 120);

    // Steps
    let yPosition = 200;
    roadmap.steps.forEach((step, index) => {
      // Step number circle
      ctx.fillStyle = '#3b82f6';
      ctx.beginPath();
      ctx.arc(100, yPosition - 10, 25, 0, 2 * Math.PI);
      ctx.fill();

      ctx.fillStyle = '#ffffff';
      ctx.font = 'bold 18px Arial';
      ctx.textAlign = 'center';
      ctx.fillText((index + 1).toString(), 100, yPosition - 5);

      // Step title
      ctx.fillStyle = '#ffffff';
      ctx.font = 'bold 28px Arial';
      ctx.textAlign = 'left';
      ctx.fillText(step.title, 160, yPosition);

      // Step description
      ctx.fillStyle = '#94a3b8';
      ctx.font = '18px Arial';
      const words = step.description.split(' ');
      let line = '';
      let lineY = yPosition + 40;
      const maxWidth = 900;

      for (let i = 0; i < words.length; i++) {
        const testLine = line + words[i] + ' ';
        const metrics = ctx.measureText(testLine);
        if (metrics.width > maxWidth && i > 0) {
          ctx.fillText(line, 160, lineY);
          line = words[i] + ' ';
          lineY += 25;
        } else {
          line = testLine;
        }
      }
      ctx.fillText(line, 160, lineY);

      // Duration
      ctx.fillStyle = '#64748b';
      ctx.font = '16px Arial';
      ctx.fillText(`Duration: ${step.duration}`, 160, lineY + 40);

      // Prerequisites
      if (step.prerequisites.length > 0) {
        ctx.fillText(`Prerequisites: ${step.prerequisites.join(', ')}`, 160, lineY + 65);
      }

      // Resources
      if (step.resources.length > 0) {
        ctx.fillStyle = '#10b981';
        ctx.font = 'bold 16px Arial';
        ctx.fillText('Resources:', 160, lineY + 95);
        ctx.fillStyle = '#94a3b8';
        ctx.font = '14px Arial';
        step.resources.forEach((resource, idx) => {
          ctx.fillText(`• ${resource}`, 180, lineY + 120 + (idx * 20));
        });
        yPosition = lineY + 140 + (step.resources.length * 20);
      } else {
        yPosition = lineY + 100;
      }

      // Add some spacing between steps
      yPosition += 60;
    });

    // Watermark
    ctx.save();
    ctx.globalAlpha = 0.1;
    ctx.fillStyle = '#3b82f6';
    ctx.font = 'bold 36px Arial';
    ctx.textAlign = 'center';
    ctx.translate(600, 800);
    ctx.rotate(-Math.PI / 6);
    ctx.fillText('TechieHelp Institute of AI', 0, 0);
    ctx.restore();

    // Footer
    ctx.fillStyle = '#64748b';
    ctx.font = '16px Arial';
    ctx.textAlign = 'center';
    ctx.fillText('Generated by TechieHelp Institute of AI - Your Career Development Partner', 600, 1550);

    // Download
    const link = document.createElement('a');
    link.download = `TechieHelp_Roadmap_${roadmap.title.replace(/\s+/g, '_')}.png`;
    link.href = canvas.toDataURL();
    link.click();

    toast.success('Roadmap downloaded successfully!');
  };

  return (
    <div className="space-y-16 py-10">
      <div className="flex flex-col items-center gap-6 mb-12">
        <h2 className="text-5xl font-black tracking-tighter text-center bg-clip-text text-transparent bg-gradient-to-r from-white via-blue-200 to-white/40 drop-shadow-2xl">
           {roadmap.title}
        </h2>
        <Button 
          onClick={downloadRoadmap} 
          className="h-14 px-10 rounded-full bg-white text-black font-black hover:bg-blue-400 transition-all shadow-[0_20px_40px_-15px_rgba(255,255,255,0.3)] flex items-center gap-3 border-none"
        >
          <Download className="h-5 w-5" />
          Download Roadmap
        </Button>
      </div>

      <div className="relative max-w-5xl mx-auto px-4 md:px-0">
        {/* Central Vertical Connector Line */}
        <div className="absolute left-[31px] md:left-1/2 top-0 bottom-0 w-[2px] bg-gradient-to-b from-blue-500/80 via-purple-500/40 to-transparent md:-translate-x-1/2 opacity-20 pointer-events-none" />

        {roadmap.steps.map((step, index) => {
          const Icon = iconMap[step.category] || iconMap.default;
          const isEven = index % 2 === 0;
          const colorClass = colors[index % colors.length];

          return (
            <div key={index} className="relative mb-24 md:mb-32">
              {/* Timeline Center Badge */}
              <div className="absolute left-0 md:left-1/2 top-0 -translate-y-1/2 md:-translate-x-1/2 z-10 flex flex-col items-center">
                 <motion.div
                    initial={{ scale: 0, rotate: -180 }}
                    whileInView={{ scale: 1, rotate: 0 }}
                    viewport={{ once: true }}
                    className={`w-16 h-16 rounded-[22px] bg-gradient-to-br ${colorClass} flex items-center justify-center p-0.5 shadow-[0_0_30px_rgba(59,130,246,0.2)]`}
                 >
                    <div className="w-full h-full bg-black/40 rounded-[20px] backdrop-blur-3xl flex items-center justify-center">
                       <Icon className="w-8 h-8 text-white" />
                    </div>
                 </motion.div>
                 <div className="mt-4 px-3 py-1 bg-white/5 border border-white/10 rounded-full text-[10px] font-black tracking-widest text-muted-foreground uppercase backdrop-blur-xl">
                   PHASE {index + 1}
                 </div>
              </div>

              {/* Step Content */}
              <div className={`flex flex-col md:flex-row items-center w-full ${isEven ? 'md:flex-row-reverse' : ''}`}>
                <div className="hidden md:block w-1/2" />
                <motion.div
                  initial={{ opacity: 0, x: isEven ? -50 : 50 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true, margin: "-100px" }}
                  transition={{ duration: 0.8, ease: "easeOut" }}
                  className={`w-full md:w-1/2 pt-12 md:pt-0 ${isEven ? 'md:pr-16 lg:pr-24' : 'md:pl-16 lg:pl-24'}`}
                >
                  <div className={`group relative p-8 lg:p-10 bg-white/5 border border-white/10 rounded-[40px] backdrop-blur-2xl hover:border-white/20 hover:bg-white/[0.08] transition-all duration-500 shadow-2xl overflow-hidden`}>
                    {/* Decorative Gradient Glow */}
                    <div className={`absolute top-0 right-0 w-32 h-32 bg-gradient-to-br ${colorClass} blur-[60px] opacity-0 group-hover:opacity-20 transition-opacity`} />
                    
                    <div className="relative z-10">
                       <h3 className="text-3xl font-black mb-4 tracking-tighter text-white group-hover:text-blue-200 transition-colors">
                         {step.title}
                       </h3>
                       <p className="text-muted-foreground mb-8 leading-relaxed font-medium">
                         {step.description}
                       </p>

                       <div className="flex flex-wrap items-center gap-3 mb-8 text-sm font-bold">
                          <span className="bg-blue-500/10 border border-blue-500/20 text-blue-400 px-4 py-1.5 rounded-xl">Duration: {step.duration}</span>
                          {step.prerequisites.length > 0 && (
                            <span className="bg-purple-500/10 border border-purple-500/20 text-purple-400 px-4 py-1.5 rounded-xl">Prerequisites: {step.prerequisites.join(", ")}</span>
                          )}
                       </div>

                       {step.resources.length > 0 && (
                         <div className="space-y-4 mb-8">
                            <h4 className="text-xs uppercase tracking-[0.3em] font-black text-white/40">Resources:</h4>
                            <ul className="space-y-3">
                               {step.resources.map((resource, idx) => (
                                 <li key={idx} className="flex items-start gap-3 group/item text-sm font-medium text-white/70">
                                    <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-emerald-400/50 group-hover/item:scale-125 transition-transform" />
                                    {resource}
                                 </li>
                               ))}
                            </ul>
                         </div>
                       )}

                       {step.videoLink && (
                         <a
                           href={step.videoLink}
                           target="_blank"
                           rel="noopener noreferrer"
                           className="inline-flex items-center px-6 py-3 bg-red-500 hover:bg-red-400 text-white rounded-2xl text-xs font-black uppercase tracking-widest transition-all shadow-[0_10px_20px_-5px_rgba(239,68,68,0.3)] hover:scale-[1.02] active:scale-95 group/btn"
                         >
                           <svg className="w-4 h-4 mr-2 group-hover/btn:scale-110 transition-transform" fill="currentColor" viewBox="0 0 24 24">
                              <path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z" />
                           </svg>
                           Watch Video Tutorial
                         </a>
                       )}
                    </div>
                  </div>
                </motion.div>
              </div>
            </div>
          );
        })}
      </div>

      {roadmap.selfGrowthTips && (
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="container mx-auto max-w-5xl px-4"
        >
          <div className="p-10 lg:p-14 bg-gradient-to-br from-white/5 to-white/[0.02] border border-white/10 rounded-[48px] backdrop-blur-2xl shadow-2xl relative overflow-hidden">
             
             <h3 className="text-4xl font-black mb-12 text-center tracking-tighter">Self-Growth Tips</h3>
             
             <div className="grid md:grid-cols-2 gap-10">
               <div className="p-8 bg-blue-500/5 border border-blue-500/10 rounded-[32px] hover:bg-blue-500/10 transition-colors">
                     <h4 className="text-xl font-black tracking-tight mb-4 text-blue-400">How to Complete the Roadmap</h4>
                  <p className="text-muted-foreground leading-relaxed font-medium">{roadmap.selfGrowthTips.howToComplete}</p>
               </div>
               
               <div className="p-8 bg-emerald-500/5 border border-emerald-500/10 rounded-[32px] hover:bg-emerald-500/10 transition-colors">
                     <h4 className="text-xl font-black tracking-tight mb-4 text-emerald-400">Stay Motivated</h4>
                  <p className="text-muted-foreground leading-relaxed font-medium">{roadmap.selfGrowthTips.motivationTips}</p>
               </div>
             </div>
          </div>
        </motion.div>
      )}

      {/* Footer Branding Overlay */}
      <div className="flex justify-center pt-20">
         <div className="inline-flex items-center gap-3 px-8 py-3 rounded-full bg-white/5 border border-white/10 backdrop-blur-xl">
            <span className="text-[10px] uppercase tracking-[0.4em] font-black text-muted-foreground/40 italic">Generated by TechieHelp <span className="text-blue-500">Institute of AI</span></span>
         </div>
      </div>
    </div>
  );
}
